import { useState } from "react";
import type { ClientConfigPlan, ClientKind, ClientStatus, DesktopResult } from "../../common/ipc";
import { EmptyState } from "./Status";

export function ClientWizard({ projectId, statuses, onClose, onError, onRefresh }: { projectId: string; statuses: ClientStatus[]; onClose(): void; onError(result: DesktopResult<unknown>): void; onRefresh(): Promise<void> }) {
  const [selected, setSelected] = useState<ClientKind>("codex");
  const [scope, setScope] = useState<"project" | "user">("project");
  const [plan, setPlan] = useState<ClientConfigPlan | null>(null);
  const [pairing, setPairing] = useState<{ profilePath: string; expiresAt: string } | null>(null);
  const [busy, setBusy] = useState(false);
  const current = statuses.find((entry) => entry.client === selected);
  const handshakeVerified = current ? /connected|handshake.*ok|revision.*read/i.test(current.diagnostic) : false;
  async function prepare() { setBusy(true); const result = await window.boxspec.generateClientConfig({ projectId, client: selected, scope }); setBusy(false); if (result.ok) setPlan(result.data); else onError(result); }
  async function apply() { if (!plan) return; setBusy(true); const result = await window.boxspec.applyClientConfig({ projectId, planId: plan.planId, expectedExistingHash: plan.expectedExistingHash }); setBusy(false); if (result.ok) { setPlan(null); await onRefresh(); } else onError(result); }
  async function diagnose() { setBusy(true); const result = await window.boxspec.diagnoseClient({ projectId, client: selected }); setBusy(false); if (result.ok) await onRefresh(); else onError(result); }
  async function pair() { setBusy(true); const result = await window.boxspec.pairClient({ projectId, client: selected }); setBusy(false); if (result.ok) setPairing(result.data); else onError(result); }
  return <div className="modal-backdrop"><section className="wizard" role="dialog" aria-modal="true" aria-labelledby="wizard-title"><header><div><h2 id="wizard-title">MCP client setup</h2><p>BoxSpec writes no credentials. Review the local configuration diff before applying it.</p></div><button type="button" onClick={onClose}>Close</button></header><nav className="wizard-clients" aria-label="MCP clients">{(["codex", "claude-code", "opencode"] as const).map((client) => { const status = statuses.find((entry) => entry.client === client); const verified = status ? /connected|handshake.*ok|revision.*read/i.test(status.diagnostic) : false; return <button type="button" key={client} className={selected === client ? "active" : ""} onClick={() => { setSelected(client); setPlan(null); setPairing(null); }}><strong>{client}</strong><span>{!status?.configured ? "Config not written" : verified ? "Handshake verified" : "Config written · not connected"}</span></button>; })}</nav><div className="wizard-body"><div className="diagnostic"><strong>{current?.configured ? "Configuration written" : "Configuration not written"} · {handshakeVerified ? "revision read verified" : "handshake unverified"}</strong><p>{current?.diagnostic ?? "No diagnostic has been run."}</p><div className="button-row"><button type="button" onClick={pair} disabled={busy}>Pair local client for 15 minutes</button><button type="button" onClick={diagnose} disabled={busy}>Run diagnostic</button></div>{pairing && <p>Pairing profile: <code>{pairing.profilePath}</code><br />Expires {pairing.expiresAt}</p>}</div><label>Configuration scope<select value={scope} onChange={(e) => setScope(e.target.value as "project" | "user")}><option value="project">Project</option><option value="user">User</option></select></label><button type="button" onClick={prepare} disabled={busy}>Prepare configuration diff</button>{plan ? <div className="config-plan"><p>Target: <code>{plan.targetPath}</code></p><pre aria-label="Configuration diff">{plan.unifiedDiff || "No textual change"}</pre><div className="button-row"><button type="button" onClick={() => setPlan(null)}>Discard</button><button type="button" className="primary" onClick={apply} disabled={busy}>Apply reviewed configuration</button></div></div> : <EmptyState title="No pending configuration" detail="Preparing a diff does not change the client configuration." />}</div></section></div>;
}
